[build]
  command = "export DATABASE_URL=$NETLIFY_DATABASE_URL && npx prisma generate && npx prisma db push --accept-data-loss && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
