const FALLBACK_PRODUCTS = [
  {
    id: '9636445421798',
    name: "SKILLDESK TITAN PRO 160",
    slug: 'skilldesk-titan-pro-160',
    description: "DÃ©couvrez le SKILLDESK TITAN PRO 160, un produit de haute qualitÃ©.",
    price: 3799.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLDESKTITANPRO160.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9636417667302',
    name: "SKILLDESK TITAN PRO 140",
    slug: 'skilldesk-titan-pro-140',
    description: "DÃ©couvrez le SKILLDESK TITAN PRO 140, un produit de haute qualitÃ©.",
    price: 3499.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLDESKTITANPRO140.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9634092384486',
    name: "Gigabyte GeForce RTX 5070 Ti GAMING OC 16Go GDDR7",
    slug: 'gigabyte-geforce-rtx-5070-ti-gaming-oc-16go-gddr7',
    description: "DÃ©couvrez le Gigabyte GeForce RTX 5070 Ti GAMING OC 16Go GDDR7, un produit de haute qualitÃ©.",
    price: 12999.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/GigabyteGeForceRTX5070TiGAMINGOC16GoGDDR7.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Gigabyte",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9634090582246',
    name: "HIKSEMI Wave PCIe 3.0 SSD 512GB (BULK)",
    slug: 'hiksemi-wave-pcie-3-0-ssd-512gb-bulk',
    description: "DÃ©couvrez le HIKSEMI Wave PCIe 3.0 SSD 512GB (BULK), un produit de haute qualitÃ©.",
    price: 799.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/HIKSEMIWavePCIe3.0SSD512GB_BULK.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "HIKSEMI",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9634075640038',
    name: "SKILLDESK COCKPIT 180",
    slug: 'skilldesk-cockpit-180',
    description: "DÃ©couvrez le SKILLDESK COCKPIT 180, un produit de haute qualitÃ©.",
    price: 1599.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLDESKCOCKPIT180.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9634074067174',
    name: "SKILLDESK COCKPIT 160",
    slug: 'skilldesk-cockpit-160',
    description: "DÃ©couvrez le SKILLDESK COCKPIT 160, un produit de haute qualitÃ©.",
    price: 1499.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLDESKCOCKPIT160.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9634072690918',
    name: "SKILLDESK WARZONE 140",
    slug: 'skilldesk-warzone-140',
    description: "DÃ©couvrez le SKILLDESK WARZONE 140, un produit de haute qualitÃ©.",
    price: 1099.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLDESKWARZONE140_325c5efe-4f90-4d5f-9328-9c5aa324a1e9.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9634033467622',
    name: "SKILLDESK STARFORGE (Motorisé)",
    slug: 'skilldesk-starforge-motorise',
    description: "DÃ©couvrez le SKILLDESK STARFORGE (Motorisé), un produit de haute qualitÃ©.",
    price: 1999.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLDESKSTARFORGE_Motorise.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9634031894758',
    name: "SKILLDESK WARZONE 160",
    slug: 'skilldesk-warzone-160',
    description: "DÃ©couvrez le SKILLDESK WARZONE 160, un produit de haute qualitÃ©.",
    price: 1199.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLDESKWARZONE160_d32e3b09-a19f-4292-ab64-c135e1dbdd58.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9634029994214',
    name: "SKILLDESK FALCON (Motorisé)",
    slug: 'skilldesk-falcon-motorise',
    description: "DÃ©couvrez le SKILLDESK FALCON (Motorisé), un produit de haute qualitÃ©.",
    price: 1999.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLDESKFALCON_Motorise.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9633566851302',
    name: "AMD Ryzen 5 7500F (3.7 GHz / 5.0 GHz) MPK",
    slug: 'amd-ryzen-5-7500f-3-7-ghz-5-0-ghz-mpk',
    description: "DÃ©couvrez le AMD Ryzen 5 7500F (3.7 GHz / 5.0 GHz) MPK, un produit de haute qualitÃ©.",
    price: 1899.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/200_3e3945ca-2572-41ec-b273-a02d4b2742fc.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "AMD",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9633533526246',
    name: "Thermal Grizzly AM5 Contact & Sealing Frame",
    slug: 'thermal-grizzly-am5-contact-sealing-frame',
    description: "DÃ©couvrez le Thermal Grizzly AM5 Contact & Sealing Frame, un produit de haute qualitÃ©.",
    price: 299.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/ThermalGrizzlyAM5Contact_SealingFrame.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Thermal Grizzly",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9463145726182',
    name: "CONNECT AIRBOOST ARGB + CONNECT PSU 650W",
    slug: 'connect-airboost-argb-connect-psu-650w',
    description: "DÃ©couvrez le CONNECT AIRBOOST ARGB + CONNECT PSU 650W, un produit de haute qualitÃ©.",
    price: 699.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/connect3_b76b8a2c-4586-4c33-a62e-4f5911d1c2ab.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Connect",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9632585679078',
    name: "Lenovo LOQ 15IRX10 i5-13450HX/16GB DDR5/512GB SSD/RTX 5050 8GB/15.6\" FHD",
    slug: 'lenovo-loq-15irx10-i5-13450hx-16gb-ddr5-512gb-ssd-rtx-5050-8gb-15-6-fhd',
    description: "DÃ©couvrez le Lenovo LOQ 15IRX10 i5-13450HX/16GB DDR5/512GB SSD/RTX 5050 8GB/15.6\" FHD, un produit de haute qualitÃ©.",
    price: 11290.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/LenovoLOQ15IRX10_003e0cef-91fe-471b-9fc7-6e151e0054d4.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Lenovo",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9632580927718',
    name: "HP Victus 15-fa2082wm i5-13420H/16GB DDR4/512GB SSD/RTX 4050 6GB/15.6\" 144Hz",
    slug: 'hp-victus-15-fa2082wm-i5-13420h-16gb-ddr4-512gb-ssd-rtx-4050-6gb-15-6-144hz',
    description: "DÃ©couvrez le HP Victus 15-fa2082wm i5-13420H/16GB DDR4/512GB SSD/RTX 4050 6GB/15.6\" 144Hz, un produit de haute qualitÃ©.",
    price: 9990.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/HPVictus15-fa2082wm_d3cf6954-e67e-4edc-8b26-00765597ed84.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "HP",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9632551796966',
    name: "Thermal Grizzly Duronaut (6 grammes)",
    slug: 'thermal-grizzly-duronaut-6-grammes',
    description: "DÃ©couvrez le Thermal Grizzly Duronaut (6 grammes), un produit de haute qualitÃ©.",
    price: 249.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/ThermalGrizzlyDuronaut_6grammes.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Thermal Grizzly",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9632550289638',
    name: "Thermal Grizzly Duronaut (2 grammes)",
    slug: 'thermal-grizzly-duronaut-2-grammes',
    description: "DÃ©couvrez le Thermal Grizzly Duronaut (2 grammes), un produit de haute qualitÃ©.",
    price: 149.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/ThermalGrizzlyDuronaut_2grammes.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Thermal Grizzly",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9632543965414',
    name: "Thermal Grizzly M2 SSD Cooler",
    slug: 'thermal-grizzly-m2-ssd-cooler',
    description: "DÃ©couvrez le Thermal Grizzly M2 SSD Cooler, un produit de haute qualitÃ©.",
    price: 199.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/ThermalGrizzlyM2SSDCooler.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Thermal Grizzly",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9632541606118',
    name: "Thermal Grizzly Ryzen 7000 Direct Die Frame V2",
    slug: 'thermal-grizzly-ryzen-7000-direct-die-frame-v2',
    description: "DÃ©couvrez le Thermal Grizzly Ryzen 7000 Direct Die Frame V2, un produit de haute qualitÃ©.",
    price: 279.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/ThermalGrizzlyRyzen7000DirectDieFrameV2.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Thermal Grizzly",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9632540295398',
    name: "ASRock Radeon RX 9070 XT Challenger 16Go (Sans emballage)",
    slug: 'asrock-radeon-rx-9070-xt-challenger-16go-sans-emballage',
    description: "DÃ©couvrez le ASRock Radeon RX 9070 XT Challenger 16Go (Sans emballage), un produit de haute qualitÃ©.",
    price: 9999.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/ASRockRadeonRX9070XTChallenger16Go_Sansemballage.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "ASROCK",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9631970263270',
    name: "XALLKING X5C-Z104 Noir",
    slug: 'xallking-x5c-z104-noir',
    description: "DÃ©couvrez le XALLKING X5C-Z104 Noir, un produit de haute qualitÃ©.",
    price: 2599.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/XALLKINGX5C-Z104Noir.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "XALLKING",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9631963578598',
    name: "XALLKING X5C-207 Noir",
    slug: 'xallking-x5c-207-noir',
    description: "DÃ©couvrez le XALLKING X5C-207 Noir, un produit de haute qualitÃ©.",
    price: 2199.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/XALLKINGX5C-207Noir.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "XALLKING",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9631320309990',
    name: "SKILLCHAIRS Ergo Milano",
    slug: 'skillchairs-ergo-milano',
    description: "DÃ©couvrez le SKILLCHAIRS Ergo Milano, un produit de haute qualitÃ©.",
    price: 1299.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLCHAIRSErgoMilano.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9631313559782',
    name: "SKILLCHAIRS Ergo Calista (Grey)",
    slug: 'skillchairs-ergo-calista-grey',
    description: "DÃ©couvrez le SKILLCHAIRS Ergo Calista (Grey), un produit de haute qualitÃ©.",
    price: 1799.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLCHAIRSErgoCalista_Grey.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9631304024294',
    name: "SKILLCHAIRS Ergo Roma",
    slug: 'skillchairs-ergo-roma',
    description: "DÃ©couvrez le SKILLCHAIRS Ergo Roma, un produit de haute qualitÃ©.",
    price: 1099.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/SKILLCHAIRSErgoRoma.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Skillchairs",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9631286264038',
    name: "Logitech Spotlight Presentation Remote Ardoise",
    slug: 'logitech-spotlight-presentation-remote-ardoise',
    description: "DÃ©couvrez le Logitech Spotlight Presentation Remote Ardoise, un produit de haute qualitÃ©.",
    price: 1299.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/LogitechSpotlightPresentationRemoteArdoise.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Logitech",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9631276204262',
    name: "Biwin M350 SSD M.2 PCIe 1To (Sans emballage)",
    slug: 'biwin-m350-ssd-m-2-pcie-1to-sans-emballage',
    description: "DÃ©couvrez le Biwin M350 SSD M.2 PCIe 1To (Sans emballage), un produit de haute qualitÃ©.",
    price: 1799.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/BiwinM350SSDM.2PCIe1To.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "BIWIN",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '8983420731622',
    name: "PC Gamer Electro Islam i9 14900K/1TB SSD/32GB/RTX 5070",
    slug: 'pc-gamer-electro-islam-i9-14900k-1tb-ssd-32gb-rtx-5070',
    description: "DÃ©couvrez le PC Gamer Electro Islam i9 14900K/1TB SSD/32GB/RTX 5070, un produit de haute qualitÃ©.",
    price: 20999.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/PCGAMER01.10.2025-Recupere-Recupere-Recupere-Recupere-Recupere-Recupere-Recupere-Recupere.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Electro Islam",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '8983421386982',
    name: "PC Gamer Electro Islam i9 14900K/1TB SSD/32GB/RTX 5070Ti",
    slug: 'pc-gamer-electro-islam-i9-14900k-1tb-ssd-32gb-rtx-5070ti',
    description: "DÃ©couvrez le PC Gamer Electro Islam i9 14900K/1TB SSD/32GB/RTX 5070Ti, un produit de haute qualitÃ©.",
    price: 25999.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/PCGAMER01.10.2025-Recupere-Recupere-Recupere-Recupere-Recupere-Recupere-Recupere-Recupere_892df8d3-0c0c-4aa4-a3e2-0d0f99ef15bb.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Electro Islam",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '8983423877350',
    name: "PC Gamer Electro Islam i9 14900K/1TB SSD/32GB/RTX 5080",
    slug: 'pc-gamer-electro-islam-i9-14900k-1tb-ssd-32gb-rtx-5080',
    description: "DÃ©couvrez le PC Gamer Electro Islam i9 14900K/1TB SSD/32GB/RTX 5080, un produit de haute qualitÃ©.",
    price: 30999.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/cvcxn.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Electro Islam",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9628008480998',
    name: "HIKVISION DDR4 8GB 2666MHz",
    slug: 'hikvision-ddr4-8gb-2666mhz',
    description: "DÃ©couvrez le HIKVISION DDR4 8GB 2666MHz, un produit de haute qualitÃ©.",
    price: 599.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/HIKVISIONDDR48GB2666MHz.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "HIKVISION",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9627937079526',
    name: "HP Victus 15-fa2712ua i5-13420H/16GB DDR4/512GB SSD/RTX3050 6GB/15.6\" 144Hz",
    slug: 'hp-victus-15-fa2712ua-i5-13420h-16gb-ddr4-512gb-ssd-rtx3050-6gb-15-6-144hz',
    description: "DÃ©couvrez le HP Victus 15-fa2712ua i5-13420H/16GB DDR4/512GB SSD/RTX3050 6GB/15.6\" 144Hz, un produit de haute qualitÃ©.",
    price: 8490.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/jjn.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "HP",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9627174600934',
    name: "Innovation IT SO-DIMM 8Go (1x8Go) DDR4 3200 MHz CL22",
    slug: 'innovation-it-so-dimm-8go-1x8go-ddr4-3200-mhz-cl22',
    description: "DÃ©couvrez le Innovation IT SO-DIMM 8Go (1x8Go) DDR4 3200 MHz CL22, un produit de haute qualitÃ©.",
    price: 799.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/InnovationITSO-DIMM8Go_1x8Go_DDR43200MHzCL22.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "INNOVATION IT",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9627170078950',
    name: "Innovation IT 8Go (1x8Go) DDR4 3200 MHz CL16",
    slug: 'innovation-it-8go-1x8go-ddr4-3200-mhz-cl16',
    description: "DÃ©couvrez le Innovation IT 8Go (1x8Go) DDR4 3200 MHz CL16, un produit de haute qualitÃ©.",
    price: 799.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/InnovationIT8Go_1x8Go_DDR43200MHzCL16.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "INNOVATION IT",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9627156414694',
    name: "Energy Sistem Gaming ESG K4 Kompact RGB",
    slug: 'energy-sistem-gaming-esg-k4-kompact-rgb',
    description: "DÃ©couvrez le Energy Sistem Gaming ESG K4 Kompact RGB, un produit de haute qualitÃ©.",
    price: 199.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/EnergySistemGamingESGK4KompactRGB.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "Energy Sistem",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9627133313254',
    name: "DIGITUS DA-90436",
    slug: 'digitus-da-90436',
    description: "DÃ©couvrez le DIGITUS DA-90436, un produit de haute qualitÃ©.",
    price: 799.00,
    stock: 15,
    inStock: true,
    images: JSON.stringify(['/images/products/DIGITUSDA-90436.png']),
    categoryId: 'composants',
    category: { id: 'composants', name: 'Composants', slug: 'composants' },
    brand: "DIGITUS",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
];

